
# Metadata shared by all documents
#
bibliography: metadata/references.bib
csl: metadata/apa.csl
copyright: 2025, University of Edinburgh
date-format: long
date-modified: last-modified
license: CC BY
